### ISSUE TITLE
правка

### ISSUE THREAD

**Issue by tallinn-learning** [VeronikaOstrovski/homework11#1]
https://github.com/VeronikaOstrovski/homework11/blob/22b66f1fa0aafa38e658c2471ea1fa444b1cce38/src/test/java/org/example/DeliveryAPITest.java#L29

давайте сделаем так
 Assumptions.assumeFalse(token.isEmpty(), "Token is not exist, all test skipped");

**Comment by VeronikaOstrovski** [comment]
Да, хорошо. Давайте так. Это более правильно считается?

**Comment by tallinn-learning** [comment]
да, мы этот на уроках еще обсудим
